# @CTRLPlusN\Modules\config.yml
services:

# Commenté une ressource pour désactiver une modulerairie
imports:
    - { resource: '@CTRLPlusN/Modules/PictureModule/config/config.yml' }
    - { resource: '@CTRLPlusN/Modules/ReviewModule/config/config.yml' }
    - { resource: '@CTRLPlusN/Modules/LinkModule/config/config.yml' }
    - { resource: '@CTRLPlusN/Modules/GuestbookModule/config/config.yml' }

parameters:
    # Réorganiser l'ordre en déplassant les noms pour l'affichage dans le menu
    modules.name:
        - review_module
        - picture_module
        - link_module
        - guestbook_module